/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type MissionCard = {
  _type: 'missionCard'
  title: string
  body: string
}

export type Feature = {
  _type: 'feature'
  icon?: string
  label: string
}

export type Benefit = {
  _type: 'benefit'
  icon?: string
  title: string
  description: string
}

export type Step = {
  _type: 'step'
  number: number
  title: string
  description: string
  icon?: string
}

export type Cta = {
  _type: 'cta'
  label: string
  href: string
  style: 'primary' | 'secondary'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  title: string
  linkType?: 'href' | 'page'
  href?: string
  page?: PageReference
  openInNewTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page'
        href?: string
        page?: PageReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type ContactSubmission = {
  _id: string
  _type: 'contactSubmission'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  message?: string
  submittedAt?: string
}

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  role: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: string
  order: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type FaqItem = {
  _id: string
  _type: 'faqItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question: string
  answer: BlockContent
  order: number
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  heading?: string
  introBody?: BlockContent
}

export type AProposPage = {
  _id: string
  _type: 'aProposPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  storyHeading?: string
  storyBody?: BlockContent
  storyImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  teamHeading?: string
  missionHeading?: string
  missionCards?: Array<
    {
      _key: string
    } & MissionCard
  >
}

export type NotreSitePage = {
  _id: string
  _type: 'notreSitePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  description?: BlockContent
  courtImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  status?: 'coming_soon' | 'open'
  statusLabel?: string
  locationLabel?: string
  features?: Array<
    {
      _key: string
    } & Feature
  >
}

export type InstallerPage = {
  _id: string
  _type: 'installerPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroHeading?: string
  heroHighlightWords?: Array<string>
  heroBody?: BlockContent
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stepsHeading?: string
  steps?: Array<
    {
      _key: string
    } & Step
  >
  benefitsHeading?: string
  benefits?: Array<
    {
      _key: string
    } & Benefit
  >
  featuresHeading?: string
  features?: Array<
    {
      _key: string
    } & Feature
  >
  ctaHeading?: string
  ctaBody?: BlockContent
  cta?: Cta
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroHeading?: string
  heroHighlightWords?: Array<string>
  heroSlogan?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  heroPrimaryCta?: Cta
  heroSecondaryCta?: Cta
  introHeading?: string
  introBody?: BlockContent
  introPrimaryCta?: Cta
  introSecondaryCta?: Cta
  factsEyebrow?: string
  factsHeading?: string
  factsBody?: string
  howItWorksHeading?: string
  howItWorksSteps?: Array<
    {
      _key: string
    } & Step
  >
  howItWorksImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  impactHeading?: string
  impactBody?: BlockContent
  impactCta?: Cta
  impactImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaBannerHeading?: string
  ctaBannerPrimaryCta?: Cta
  ctaBannerSecondaryCta?: Cta
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  eyebrow?: string
  subtitle?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  body?: BlockContent
  metaTitle?: string
  metaDescription?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  navLinks?: Array<
    {
      _key: string
    } & Link
  >
  footerLinks?: Array<
    {
      _key: string
    } & Link
  >
  socialInstagram?: string
  socialFacebook?: string
  contactEmail?: string
  copyrightText?: string
  googleAnalyticsId?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MissionCard
  | Feature
  | Benefit
  | Step
  | Cta
  | PageReference
  | Link
  | SanityImageAssetReference
  | BlockContent
  | ContactSubmission
  | TeamMember
  | SanityImageCrop
  | SanityImageHotspot
  | FaqItem
  | ContactPage
  | AProposPage
  | NotreSitePage
  | InstallerPage
  | HomePage
  | Page
  | Slug
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "settings"][0]
export type SiteSettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  navLinks?: Array<
    {
      _key: string
    } & Link
  >
  footerLinks?: Array<
    {
      _key: string
    } & Link
  >
  socialInstagram?: string
  socialFacebook?: string
  contactEmail?: string
  copyrightText?: string
  googleAnalyticsId?: string
} | null

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]
export type HomePageQueryResult = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroHeading?: string
  heroHighlightWords?: Array<string>
  heroSlogan?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  heroPrimaryCta?: Cta
  heroSecondaryCta?: Cta
  introHeading?: string
  introBody?: BlockContent
  introPrimaryCta?: Cta
  introSecondaryCta?: Cta
  factsEyebrow?: string
  factsHeading?: string
  factsBody?: string
  howItWorksHeading?: string
  howItWorksSteps?: Array<
    {
      _key: string
    } & Step
  >
  howItWorksImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  impactHeading?: string
  impactBody?: BlockContent
  impactCta?: Cta
  impactImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaBannerHeading?: string
  ctaBannerPrimaryCta?: Cta
  ctaBannerSecondaryCta?: Cta
} | null

// Source: sanity/lib/queries.ts
// Variable: faqItemsQuery
// Query: *[_type == "faqItem"] | order(order asc)
export type FaqItemsQueryResult = Array<{
  _id: string
  _type: 'faqItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question: string
  answer: BlockContent
  order: number
}>

// Source: sanity/lib/queries.ts
// Variable: installerPageQuery
// Query: *[_type == "installerPage"][0]
export type InstallerPageQueryResult = {
  _id: string
  _type: 'installerPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroHeading?: string
  heroHighlightWords?: Array<string>
  heroBody?: BlockContent
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stepsHeading?: string
  steps?: Array<
    {
      _key: string
    } & Step
  >
  benefitsHeading?: string
  benefits?: Array<
    {
      _key: string
    } & Benefit
  >
  featuresHeading?: string
  features?: Array<
    {
      _key: string
    } & Feature
  >
  ctaHeading?: string
  ctaBody?: BlockContent
  cta?: Cta
} | null

// Source: sanity/lib/queries.ts
// Variable: notreSitePageQuery
// Query: *[_type == "notreSitePage"][0]
export type NotreSitePageQueryResult = {
  _id: string
  _type: 'notreSitePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  description?: BlockContent
  courtImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  status?: 'coming_soon' | 'open'
  statusLabel?: string
  locationLabel?: string
  features?: Array<
    {
      _key: string
    } & Feature
  >
} | null

// Source: sanity/lib/queries.ts
// Variable: aProposPageQuery
// Query: *[_type == "aProposPage"][0]
export type AProposPageQueryResult = {
  _id: string
  _type: 'aProposPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  storyHeading?: string
  storyBody?: BlockContent
  storyImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  teamHeading?: string
  missionHeading?: string
  missionCards?: Array<
    {
      _key: string
    } & MissionCard
  >
} | null

// Source: sanity/lib/queries.ts
// Variable: teamMembersQuery
// Query: *[_type == "teamMember"] | order(order asc)
export type TeamMembersQueryResult = Array<{
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  role: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: string
  order: number
}>

// Source: sanity/lib/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]
export type ContactPageQueryResult = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  metaDescription?: string
  heading?: string
  introBody?: BlockContent
} | null

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    eyebrow,    subtitle,    heroImage{..., asset->{_id, url, metadata{lqip, dimensions}}},    metaTitle,    metaDescription,    body  }
export type PageBySlugQueryResult = {
  _id: string
  title: string
  eyebrow: string | null
  subtitle: string | null
  heroImage: {
    asset: {
      _id: string
      url: string
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  metaTitle: string | null
  metaDescription: string | null
  body: BlockContent | null
} | null

// Source: sanity/lib/queries.ts
// Variable: allPageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)]{"slug": slug.current}
export type AllPageSlugsQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: sitemapDataQuery
// Query: *[_type == "page" && defined(slug.current)]{ "slug": slug.current, _updatedAt }
export type SitemapDataQueryResult = Array<{
  slug: string
  _updatedAt: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SiteSettingsQueryResult
    '*[_type == "homePage"][0]': HomePageQueryResult
    '*[_type == "faqItem"] | order(order asc)': FaqItemsQueryResult
    '*[_type == "installerPage"][0]': InstallerPageQueryResult
    '*[_type == "notreSitePage"][0]': NotreSitePageQueryResult
    '*[_type == "aProposPage"][0]': AProposPageQueryResult
    '*[_type == "teamMember"] | order(order asc)': TeamMembersQueryResult
    '*[_type == "contactPage"][0]': ContactPageQueryResult
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    eyebrow,\n    subtitle,\n    heroImage{..., asset->{_id, url, metadata{lqip, dimensions}}},\n    metaTitle,\n    metaDescription,\n    body\n  }': PageBySlugQueryResult
    '*[_type == "page" && defined(slug.current)]{"slug": slug.current}': AllPageSlugsQueryResult
    '*[_type == "page" && defined(slug.current)]{ "slug": slug.current, _updatedAt }': SitemapDataQueryResult
  }
}
